### ISSUE TITLE
Can't run prisma-starter

### ISSUE THREAD

**Issue by joeshub** [prisma/web#1898]
When trying to run the [starter project](https://www.prisma.io/docs/getting-started/quickstart) I'm getting the following error

Looks to be related to a missing type `@types/node/package.json`

Does anyone know how to fix this error? 

```
➜  prisma-starter npm run dev

> script@ dev /Users/joe/nestjs/prisma-starter
> ts-node ./script.ts

Error: Cannot find module '@types/node/package.json'
Require stack:
- /Users/joe/nestjs/prisma-starter/node_modules/ts-node/dist/index.js
- /Users/joe/nestjs/prisma-starter/node_modules/ts-node/dist/repl.js
- /Users/joe/nestjs/prisma-starter/node_modules/ts-node/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at /Users/joe/nestjs/prisma-starter/node_modules/ts-node/src/index.ts:746:52
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/joe/nestjs/prisma-starter/node_modules/ts-node/src/index.ts:734:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/joe/nestjs/prisma-starter/node_modules/typescript/lib/typescript.js:109514:143)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/joe/nestjs/prisma-starter/node_modules/typescript/lib/typescript.js:109773:26)
    at processTypeReferenceDirectives (/Users/joe/nestjs/prisma-starter/node_modules/typescript/lib/typescript.js:111223:31)
    at findSourceFileWorker (/Users/joe/nestjs/prisma-starter/node_modules/typescript/lib/typescript.js:111107:21)
    at findSourceFile (/Users/joe/nestjs/prisma-starter/node_modules/typescript/lib/typescript.js:110974:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! script@ dev: `ts-node ./script.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the script@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joe/.npm/_logs/2021-06-17T21_11_32_586Z-debug.log
```

**Comment by joeshub** [comment]
I figured it out, looks like there is a missing type dependency. To fix it just run

```
npm i -D @types/node
```

and then you can run `npm run dev` without any issues.

It might be good to add this to the repo?

**Comment by molebox** [comment]
Thanks for reporting this @joeshub , odd that this wasn't in the project. Will investigate!
