### ISSUE TITLE
Document user facing errors

### ISSUE THREAD

**Issue by Jolg42** [prisma/web#635]
```
  PrismaClientKnownRequestError
  PrismaClientUnknownRequestError
  PrismaClientRustPanicError
  PrismaClientInitializationError
  PrismaClientValidationError
```

Can be used like this ([example from here](https://github.com/prisma/prisma/blob/d9cc37b15c84070d4de74aea6d3eb3314856293d/src/packages/client/src/__tests__/runtime-tests/blog/index.js)):

The first time the unique condition on email will be valid, but if you run a second time it will throw because you can't create another user with the same email.
```ts
const {
  PrismaClient,
  PrismaClientValidationError,
  PrismaClientKnownRequestError,
} = require('@prisma/client')

async function main() {
  // Test known request error
  try {
    const result = await db.user.create({
      data: {
        email: 'a@a.de',
        name: 'Alice',
      },
    })
  } catch (e) {
    if (e instanceof PrismaClientKnownRequestError) {
      console.log("We just catched a PrismaClientKnownRequestError")
    }
  }
}

main()
```

The internal types (shows that only PrismaClientKnownRequestError has a code):
```ts
export declare class PrismaClientKnownRequestError extends Error {
  code: string;
  meta?: object;
  constructor(message: string, code: string, meta?: any);
}

export declare class PrismaClientUnknownRequestError extends Error {
  constructor(message: string);
}

export declare class PrismaClientRustPanicError extends Error {
    constructor(message: string);
}

export declare class PrismaClientInitializationError extends Error {
    constructor(message: string);
}

export declare class PrismaClientValidationError extends Error {
    constructor(message: string);
}
```

Related https://github.com/prisma/docs/issues/547

**Comment by tomhoule** [comment]
For the user-facing errors in the engines, copy-pasting a message from slack: It was a design decision when we implemented the engines user facing errors that we should be able to automatically generate up-to-date docs for these, and that they should be editable by pretty much anyone. It's not there at the moment, but they were designed with that in mind.

[Implementation](https://github.com/prisma/prisma-engines/tree/master/libs/user-facing-errors) for reference.

**Comment by mhwelander** [comment]
Related #547

**Comment by Albert-Gao** [comment]
I am not quite follow the discussion here,

my current use case is:

When use nexus framework + prisma combo, when I have an error from the backend api

```json
{
  "errors": [
    {
      "message": "\nInvalid `ctx.db.user.update()` invocation in\n/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\n\n   5 definition(t) {\n   6   t.field('testPrisma', {\n   7     type: 'User',\n   8     resolve: (_, __, ctx) => {\n→  9       return ctx.db.user.update(\n  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testPrisma"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "P2016",
          "meta": {
            "details": "Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")"
          },
          "stacktrace": [
            "Error: ",
            "\u001b[31mInvalid \u001b[1m`ctx.db.user.update()`\u001b[22m invocation in\u001b[39m",
            "\u001b[31m\u001b[4m/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\u001b[24m\u001b[39m",
            "",
            "\u001b[2m  \u001b[90m 5 \u001b[39mdefinition(t) {\u001b[22m",
            "\u001b[2m  \u001b[90m 6 \u001b[39m  t.field('testPrisma', {\u001b[22m",
            "\u001b[2m  \u001b[90m 7 \u001b[39m    type: 'User',\u001b[22m",
            "\u001b[2m  \u001b[90m 8 \u001b[39m    resolve: (_, __, ctx) => {\u001b[22m",
            "\u001b[31m\u001b[1m→\u001b[22m\u001b[39m \u001b[2m\u001b[90m 9 \u001b[39m      return ctx.db.user.update(\u001b[22m",
            "  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
            "    at PrismaClientFetcher.request (/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1212:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "testPrisma": null
  }
}
```

Is there any way I can do to identify what kind of error is this without matching hardcode string from the error message?

Isn't something like ErrorCode enum or a const object make it easier? Or I am miss something here.

Thanks :)

**Comment by janpio** [comment]
Can you please open a new issue about this @Albert-Gao in https://github.com/prisma/prisma? We are happy to answer and fix this and return a proper error.

**Comment by Albert-Gao** [comment]
Thanks 

https://github.com/prisma/prisma/issues/3488

Commented here 😀
